[colors.bright]
black = "#595959"
blue = "#79a8ff"
cyan = "#6ae4b9"
green = "#70b900"
magenta = "#b6a0ff"
red = "#ef8b50"
white = "#ffffff"
yellow = "#c0c530"

[colors.normal]
black = "#000000"
blue = "#2fafff"
cyan = "#00d3d0"
green = "#44bc44"
magenta = "#feacd0"
red = "#ff8059"
white = "#bfbfbf"
yellow = "#d0bc00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
family = "Fira Code"

[[hints.enabled]]
command = "xdg-open"
post_processing = true

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[terminal]

[terminal.shell]
program = "/usr/bin/fish"
