# A package list for Fedora workstations.
#
# Run the playbook:
#   $ ansible-playbook playbook.yml
---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  remote_user: root
  tasks:
      - name: print out the hostname of target
        command: hostname

      - name: install zsh
        package:
            name: zsh
            state: present

      - name: Add me as a user
        user:
            name: ewk
            shell: /bin/zsh
            groups: wheel

      - name: Install some packages
        ignore_errors: yes
        package:
            name:
                - aspell-en
                - bison
                - bc
                - ccache
                - clang
                - chromium
                - ctags
                - elfutils-libelf-devel
                - emacs
                - flex
                - gnome-tweaks
                - git
                - google-droid-sans-mono-fonts
                - google-noto-emoji-fonts
                - goobook
                - isync
                - keepassx
                - keychain
                - msmtp
                - mutt
                - neovim
                - notmuch
                - openssl-devel
                - perf
                - python3-markdown
                - python3-sphinx
                - ripgrep
                - rsync
                - strace
                - sysstat
                - tk
                - tmux
                - valgrind
                - w3m
                - weechat
                - xclip
                - texlive
                - texlive-isodate
                - texlive-latex
                - texlive-textpos
                - texlive-xetex
                - virtualenv
            state: present

# Usually requires rpmfusion
      - name: Install RPMFusion packages
        ignore_errors: yes
        package:
            name:
                - gstreamer1-libav
                - gstreamer1-plugins-bad-free-extras
                - gstreamer1-plugins-bad-freeworld
                - gstreamer1-plugins-bad-nonfree
                - gstreamer1-plugins-ugly
                - vlc
            state: present

